i-go-algo/i-go-algo

- BOJ/01003-피보나치_함수/01003-피보나치_함수-yoonseok.py
- BOJ/01012-유기농_배추/01012-유기농_배추-yoonseok.py
- BOJ/01074-Z/01074-Z-yoonseok.py
- BOJ/01107-리모컨/01107-리모컨-yoonseok.py
- BOJ/01260-DFS와_BFS/01260-DFS와_BFS-yoonseok.py
- BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-yoonseok.py
- BOJ/01463-1로_만들기/01463-1로_만들기-yoonseok.py
- [BOJ] 01003 피보나치 함수
- [BOJ] 01012 유기농 배추
<br />
<br />
* 0은 [1,0]로 시작하는 피보나치 수열
* 1은 [0,1]로 시작하는 피보나치 수열
* dp로 수열 값들 저장하면서 기록된 값 출력
<br/>
* 배추가 있고 체크가 안된 칸에 도착하면 answer값을 1씩 더해주고 bfs를 사용해 연결된 배추칸들을 체크합니다.
* 그 외의 칸은 스킵합니다.
<br />
<br />
112ms
O(N)
1632ms
O(N*M)
<br />
<br />
오랜만에 출력하려니까 실수가 잦았습니다. 출력미스..랑.. 인덱스 미스..
> 22.06.24(yoonseok)

- BOJ/01003-피보나치_함수/01003-피보나치_함수-changjun.py
- BOJ/01012-유기농_배추/01012-유기농_배추-changjun.py
- BOJ/01074-Z/01074-Z-changjun.py
- BOJ/01107-리모컨/01107-리모컨-changjun.py
- BOJ/01260-DFS와_BFS/01260-DFS와_BFS-changjun.py
- BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-changjun.py
- BOJ/01463-1로_만들기/01463-1로_만들기-changjun.py
<br />
<br />
<br />
<br />
- 116ms (Pypy3)
- 204ms (Pypy3)
- 112ms (Pypy3)
<br />
<br />
> 22.06.23 (changjun)

- BOJ/01541-잃어버린_괄호/01541-잃어버린_괄호-yeonju.py
- BOJ/01620-나는야_포켓몬_마스터_이다솜/01620-나는야_포켓몬_마스터_이다솜-yeonju.py
- BOJ/01676-팩토리얼_0의_개수/01676-팩토리얼_0의_개수-yeonju.py
- BOJ/01697-숨바꼭질/01697-숨바꼭질-yeonju.py
- BOJ/01764-듣보잡/01764-듣보잡-yeonju.py
- BOJ/01780-종이의_개수/01780-종이의_개수-yeonju.py
- BOJ/01927-최소_힙/01927-최소_힙-yeonju.py
* 최솟값을 만드려면 - 를 기준으로 괄호를 생성하면 됩니다.
* e.g.) 55 + 34 - (34 + 342) - (543 + 32)
<br />
* dictionary 를 생성해서 (key : 포켓몬 이름-  value: 번호) 와 (key: 번호 -  value: 포켓몬 이름) 을 모두 저장합니다.
<br />
* 2와 5의 개수를 구합니다. 2 와 5 의 쌍의 개수를 찾아서 정답으로 출력합니다.
<br />
* x - 1, x + 1, x * 2 총 3가지의 경우를 bfs 로 탐색합니다.
* 다음 위치에 해당하는 dist 리스트의 값이 0 이었던 경우에만 기존 거리의 값에서 + 1 해줍니다.
<br />
* 이름을 들어보지 못해본 사람을 다 입력 받은 후, 이름을 보지도 못한 사람의 input 을 받을 때 들어본 적 있는 사람인 경우 새로운 set 인 both 에 add 시켜줍니다.
* 풀고 나서 생각해보니 집합의 & 연산자를 이용해서 합집합으로 구해줘도 됐었더군요. 
* 시간은 & 연산자를 이용한 게 조금 더 빨랐습니다.
<br />
* 말 그대로 우선순위 큐 기본 문제 
<br />
> 22.06.30 (yeonju)

- BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-eonyong.py
- BOJ/01541-잃어버린_괄호/01541-잃어버린_괄호-eonyong.py
- BOJ/01620-나는야_포켓몬_마스터_이다솜/01620-나는야_포켓몬_마스터_이다솜-eonyong.py
- BOJ/01676-팩토리얼_0의_개수/01676-팩토리얼_0의_개수-eonyong.py
- BOJ/01697-숨바꼭질/01697-숨바꼭질-eonyong.py
- BOJ/01764-듣보잡/01764-듣보잡-eonyong.py
- BOJ/01927-최소_힙/01927-최소_힙-eonyong.py
> 22.07.02 (eonyong)

- BOJ/01541-잃어버린_괄호/01541-잃어버린_괄호-changjun.py
- BOJ/01620-나는야_포켓몬_마스터_이다솜/01620-나는야_포켓몬_마스터_이다솜-changjun.py
- BOJ/01676-팩토리얼_0의_개수/01676-팩토리얼_0의_개수-changjun.py
- BOJ/01697-숨바꼭질/01697-숨바꼭질-changjun.py
- BOJ/01764-듣보잡/01764-듣보잡-changjun.py
- BOJ/01780-종이의_개수/01780-종이의_개수-changjun.py
- BOJ/01927-최소_힙/01927-최소_힙-changjun.py
이번주 문제는 (아직까지는) 아이디어에 대한 문제가 많은듯.
> 22.07.02 (changjun)

- BOJ/01541-잃어버린_괄호/01541-잃어버린_괄호-yoonseok.py
- BOJ/01620-나는야_포켓몬_마스터_이다솜/01620-나는야_포켓몬_마스터_이다솜-yoonseok.py
- BOJ/01676-팩토리얼_0의_개수/01676-팩토리얼_0의_개수-yoonseok.py
- BOJ/01697-숨바꼭질/01697-숨바꼭질-yoonseok.py
- BOJ/01764-듣보잡/01764-듣보잡-yoonseok.py
> 22.06.30 (yoonseok)

- BOJ/01931-회의실_배정/01931-회의실_배정-yoonseok.py
- BOJ/02606-바이러스/02606-바이러스-yoonseok.py
- BOJ/02630-색종이_만들기/02630-색종이_만들기-yoonseok.py
- BOJ/07576-토마토/07576-토마토-yoonseok.py
- BOJ/07662-이중_우선순위_큐/07662-이중_우선순위_큐-yoonseok.py
> 22.07.10 (yoonseok)

- BOJ/01043-거짓말/01043-거짓말-eonyong.py
- BOJ/01149-RGB거리/01149-RGB거리-eonyong.py
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
> 22.07.18 (eonyong)

- BOJ/01043-거짓말/01043-거짓말-changjun.py
- BOJ/01149-RGB거리/01149-RGB거리-changjun.py
- BOJ/01238-파티/01238-파티-changjun.py
- BOJ/01504-특정한_최단_경로/01504-특정한_최단_경로-changjun.py
- BOJ/01629-곱셈/01629-곱셈-changjun.py
- BOJ/01753-최단경로/01753-최단경로-changjun.py
- 상호 배타 집합을 이용한 풀이 : 거짓말을 한 사람들을 하나의 set으로 묶어서 판단
<br/>
- 첫번째 시도 : dfs -> 시간초과
- 두번째 시도 : greedy?
<br/>
<br/>
<br/>
<br/>
- 첫번째 시도 : 그냥 반복
- 두번째 시도 : 그 반 나눠서 하는거....!
<br/>
<br/>
> 22.07.16 (changjun)

- BOJ/01043-거짓말/01043-거짓말-yeonju.py
- BOJ/01167-트리의_지름/01167-트리의_지름-yeonju.py
- BOJ/01629-곱셈/01629-곱셈-yeonju.py
- BOJ/01753-최단경로/01753-최단경로-yeonju.py
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
> 22.07.17 (yeonju)

- BOJ/01629-곱셈/01629-곱셈-yoonseok.py
- BOJ/01865-웜홀/01865-웜홀-yoonseok.py
- BOJ/01918-후위_표기식/01918-후위_표기식-yoonseok.py
- BOJ/01932-정수_삼각형/01932-정수_삼각형-yoonseok.py
- BOJ/01991-트리_순회/01991-트리_순회-yoonseok.py
- BOJ/02096-내려가기/02096-내려가기-yoonseok.py
> 22.07.23 (yoonseok)

- BOJ/01916-최소비용_구하기/01916-최소비용_구하기-changjun.py
- BOJ/01932-정수_삼각형/01932-정수_삼각형-changjun.py
- BOJ/01967-트리의_지름/01967-트리의_지름-changjun.py
- BOJ/02096-내려가기/02096-내려가기-changjun.py
> 22.07.27 (Changjun)

- BOJ/01916-최소비용_구하기/01916-최소비용_구하기-yeonju.py
- BOJ/01932-정수_삼각형/01932-정수_삼각형-yeonju.py
- BOJ/01967-트리의_지름/01967-트리의_지름-yeonju.py
- BOJ/02096-내려가기/02096-내려가기-yeonju.py
> merge conflict 해결 (Yeonju)

- BOJ/02407-조합/02407-조합-eonyong.py
- BOJ/02448-별_찍기_-_11/02448-별_찍기_-_11-eonyong.py
- BOJ/02638-치즈/02638-치즈-eonyong.py
- BOJ/09251-LCS/09251-LCS-eonyong.py
> 22.08.04 (Eonyong)

- BOJ/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-yoonseok.py
- BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
- BOJ/02407-조합/02407-조합-yoonseok.py
- BOJ/09251-LCS/09251-LCS-yoonseok.py
> 22.07.31 (Yoon seok)

- BOJ/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-yeonju.py
- BOJ/02407-조합/02407-조합-yeonju.py
- BOJ/02638-치즈/02638-치즈-yeonju.py
- BOJ/05639-이진_검색_트리/05639-이진_검색_트리-yeonju.py
- BOJ/09251-LCS/09251-LCS-yeonju.py
* dfs 로 아무리 지지고 볶아도 안 되는 문제 🥘 <- 다 탐색해야 하기에 시간 초과 남
* 제가 dfs 와 bfs 를 정확히 언제 써야하는 지 아직 개념이 잡혀있지 않다는 걸 깨닫게 되었습니다. 앞으로 좀 유의하면서 공부해야할 거 같군요,,
* 결론적으로 bfs 를 써야 했습니다.
* 3차원 visited 를 만든 후, 맨 마지막 원소를 벽을 부순 적 있는 경우와 부순 적 없는 경우로 나눠줘서 둘을 동시에 관리하며 가는 게 관건이었던 문제 같아요.
* 그 다음 칸 방문한 적 없는데 벽이야? -> 이전에 벽 부순 적 있어? 
1) No. 부순 적 없으면 가도 돼
2) Yes. 부순 적 있으면 못 가지
* 그 다음 칸 방문한 적 없는데 벽 아니야? -> 이전에 벽 부순 적 있어?
1) No. 벽 부순 적 없는 경우에 추가해
2) Yes. 벽 부순 적 있는 경우에 추가해
* 10C3 이면 그냥 (10 * 9 * 8) // (3 * 2 *  1) 을 해주면 된다고 코드를 짰습니다.
* 너무 쉬운 거 같아서 시간 초과 나려나? 싶었는데 잘 통과했습니다 ㅋ🦔🐡ㅋ
* 치즈 내부에 있는 애들을 어떻게 처리해줄 지가 고민스러웠습니다. 근데 생각보다 심플하더군요 ! 신기했습니다.
* 치즈가 없는 영역을 탐색하면서, 치즈가 없는 칸의 인덱스는 queue 에 넣어 탐색을 해줍니다. (물론 치즈가 없는 칸 중 지나간 곳에 대해선 방문 처리해줘야 함) 
* 반면, 치즈가 들어있는 칸은 queue 에 넣지 않고, 칸의 개수만 + 1씩 해줘서 공기와 닿는 면의 개수를 하나 늘려줍니다.
* 3 이상이 되면 공기와 2면 이상 …
> 22.07.30 (Yeonju)

- BOJ/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-changjun.py
- BOJ/02407-조합/02407-조합-changjun.py
- BOJ/02638-치즈/02638-치즈-changjun.py
- BOJ/09251-LCS/09251-LCS-changjun.py
- bfs, 벽에 대한 flag 세우기
- fact계산, 큰 수에서 int() 이상하게 동작하는듯 ...!
> 22.07.31 (Changjun) 

- BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
- BOJ/02407-조합/02407-조합-yoonseok.py
- BOJ/09465-스티커/09465-스티커-yoonseok.py
- BOJ/09663-N-Queen/09663-N-Queen-yoonseok.py
- BOJ/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yoonseok.py
- BOJ/11404-플로이드/11404-플로이드-yoonseok.py
> 22.08.10 (Yoon seok)

- BOJ/09465-스티커/09465-스티커-yeonju.py
- BOJ/09663-N-Queen/09663-N-Queen-yeonju.py
- BOJ/09935-문자열_폭발/09935-문자열_폭발-yeonju.py
- BOJ/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yeonju.py
- BOJ/11404-플로이드/11404-플로이드-yeonju.py
[아이디어]
* 앞의 열에서부터 전 열에서 가져올 수 있는 스티커의 누적 최댓값을 가져오면 됩니다.
* 그리고 맨 마지막 열의 인덱스 중 더 큰 값을 출력해주면 됩니다.
* 첫 번째 인덱스 열로 가져올 수 있는 값은 하나입니다. (바로 전 대각선 값) 
* 두 번째 인덱스 열부터 가져울 수 있는 경우의 수 2개 중 더 큰 값을 채택합니다. (바로 전 대각선 값, 전전 대각선 값 중 더 큰 것)
[아이디어]
* stack 을 이용해서 풉니다.
* 리스트에 string 각각의 문자 하나 씩을 추가해 나가는데, 만약 문자가 폭발 글자의 마지막 글자와 동일하다면 아래 사항을 확인합니다.
* 만약에 폭발 문자열의 문자들과 리스트의 폭발 문자열의 길이만큼의 마지막 문자들이 동일하다면, pop() 을 통해 폭발시켜 줍니다. 
* 문자열을 다 돌 때까지 위의 과정을 반복합니다.
[느낀 점]
* 슬라이싱 연습을 더 해야 문제 푸는 시간을 더 단축시킬 수 있을 것 같네요,, 매번 헷갈려하네요 😃 
* st = [1, 2, 3, 4, 5, 6, 7]
* print(st[-3:]) // [6, 7, 8]
[아이디어]
* dp 로 풉니다.
* dp 기본값으로 싹 다 1씩 주고 시작합니다.
* for 문을 통해 하나의 인덱스를 선택했을 때 해당 인덱스보다 위치적으로 앞에 있는 값들과 일일이 비교를 해줍니다.
* 비교를 통해 dp 값을 업데이트 시킵니다. 
[아이디어]
* 🚨 플로이드 워셜이 가물가물해서 문제 풀이법 그대로 참고해서 풀었습니다.
* a -> b 로 가는 방법이 여러 개가 주어질 수 있기에, 그 중 최소값 하나만 행렬에 …
> 22.08.07 (Yeonju)

- BOJ/02407-조합/02407-조합-eonyong.py
- BOJ/09663-N-Queen/09663-N-Queen-eonyong.py
- BOJ/09935-문자열_폭발/09935-문자열_폭발-eonyong.py
- BOJ/10830-행렬_제곱/10830-행렬_제곱-eonyong.py
- BOJ/11404-플로이드/11404-플로이드-eonyong.py
이건 제 인내심이 폭발할거같아서 블로그를 참고 했습니다. 뭔가 더 줄일 수 있을거 깉은데 방법이 안떠오르네요
> 22.08.07 (Eonyong)

- BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yeonju.py
- BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-yeonju.py
- BOJ/12851-숨바꼭질_2/12851-숨바꼭질_2-yeonju.py
- BOJ/12865-평범한_배낭/12865-평범한_배낭-yeonju.py
[아이디어]
* 행 별로 처리해주고, 그 값들을 다 더했습니다.
* 행렬의 값이 들어올 때, 각 행 별로 0번째 인덱스에서부터 해당 열까지의 누적 값을 행렬에 바로 저장해줍니다.
* e.g.) [1, 2, 3, 4] 라면 [1, 3(= 1 + 2), 6(= 3 + 3), 10(= 6 + 4)]으로 대신 저장해놓기
* (2, 2) ~ (3, 4)까지의 누적합을 구해야하는 경우, 결국 2번째 열의 누적합 + 3번째 열의 누적합을 구해서 더하게 되는 것입니다.
* 해당 행의 2번째 열 ~ 4번째 열의 누적합이 필요하기에, 4번째까지 더해놓았던 누적합에서 1번째 열의 누적합을 빼주면 됩니다.
* e.g.) [1, 3, 6, 10] 에서 2,3,4 열의 값만 필요하기에 10 - 1 해서 해당 행에서 9의 값을 얻습니다.
* 아이디어 적다보니 제 설명이 참 구리네요 darn... 
[느낀 점] 
* 맨 왼쪽 위가 1,1 이어서 인덱스 때문에 코드에서 -1, -2 처리하는 게 가독성이 별론데 흠 리팩토링 해봐야 겠어요 🤔 
[기타]
* pypy 안 쓰면 시간  초과 나네요.
[아이디어]
* parent라는 이름의 defaultdict을 노드의 개수만큼 만들었습니다.
* 각각 노드들의 부모 노드를 너비 우선 탐색을 통해 해당 key의 value 값으로 업데이트 시켜줍니다. 
* bfs로 1부터 탐색을 시작하면, 해당 노드의 자식 노드들을 구할 수 있기 때문이죠.. 
* 방문 여부 체크와 딕셔너리 parent 내 해당 key의 value 값 업데이트 유무를 통해 바로 밑 자식인지 아닌지를 확인할 수 있습니다.
[느낀 점] …
> 22.08.15 (Yeonju)

- BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-eonyong.py
- BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-eonyong.py
- BOJ/11779-최소비용_구하기_2/11779-최소비용_구하기_2-eonyong.py
- BOJ/12865-평범한_배낭/12865-평범한_배낭-eonyong.py
> 22.08.14 (eonyong)

- BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-changjun.py
- BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-changjun.py
- BOJ/12851-숨바꼭질_2/12851-숨바꼭질_2-changjun.py
- BOJ/12865-평범한_배낭/12865-평범한_배낭-changjun.py
- sys.std,readline을 안써서 시간초과가 났다 ^^
- 재귀로 했다가 recursion 에러가 났었다. input 사이즈 보고 뭐쓸지 생각해야겠다.
- 같은 시간 체크하는 방식때문에 몇번 틀렸다.
> 22.08.14 (Changjun)

- BOJ/11444-피보나치_수_6/11444-피보나치_수_6-yoonseok.py
- BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yoonseok.py
- BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-yoonseok.py
- BOJ/12865-평범한_배낭/12865-평범한_배낭-yoonseok.py
> 22.08.14 (Yoonseok)

- BOJ/14502-연구소/14502-연구소-eonyong.py
- BOJ/15650-N과_M_(2)/15650-N과_M_(2)-eonyong.py
- BOJ/15652-N과_M_(4)/15652-N과_M_(4)-eonyong.py
- BOJ/15654-N과_M_(5)/15654-N과_M_(5)-eonyong.py
- BOJ/15657-N과_M_(8)/15657-N과_M_(8)-eonyong.py
- BOJ/15663-N과_M_(9)/15663-N과_M_(9)-eonyong.py
- BOJ/15666-N과_M_(12)/15666-N과_M_(12)-eonyong.py
> 22.08.20 (Eonyong)

- BOJ/15650-N과_M_(2)/15650-N과_M_(2)-changjun.py
- BOJ/15652-N과_M_(4)/15652-N과_M_(4)-changjun.py
- BOJ/15654-N과_M_(5)/15654-N과_M_(5)-changjun.py
- BOJ/15657-N과_M_(8)/15657-N과_M_(8)-changjun.py
- BOJ/15663-N과_M_(9)/15663-N과_M_(9)-changjun.py
- BOJ/15666-N과_M_(12)/15666-N과_M_(12)-changjun.py
> 22.08.20 (Changjun)

- BOJ/13549-숨바꼭질_3/13549-숨바꼭질_3-yoonseok.py
- BOJ/14938-서강그라운드/14938-서강그라운드-yoonseok.py
- BOJ/15650-N과_M_(2)/15650-N과_M_(2)-yoonseok.py
- BOJ/15652-N과_M_(4)/15652-N과_M_(4)-yoonseok.py
> 22.08.22 (Yoonseok)

- BOJ/15686-치킨_배달/15686-치킨_배달-yeonju.py
- BOJ/16953-A_→_B/16953-A_→_B-yeonju.py
[아이디어]
* bfs
* 근데 여기서 visited 를 미리 만들어 놓은 배열이 아닌 defaultdict로 곁들인...
[느낀점]
* 창준님이 알려주신 defaultdict 늘 너무 유익하게 쓴다능... defaultdict과 창준님 만쉐이~
> 22.08.29 (yeonju)

- BOJ/15686-치킨_배달/15686-치킨_배달-changjun.py
- BOJ/16953-A_→_B/16953-A_→_B-changjun.py
- BOJ/17070-파이프_옮기기_1/17070-파이프_옮기기_1-changjun.py
> 22.08.27(Changjun)

- BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
- BOJ/11404-플로이드/11404-플로이드-yoonseok.py
- BOJ/13549-숨바꼭질_3/13549-숨바꼭질_3-yoonseok.py
- BOJ/14938-서강그라운드/14938-서강그라운드-yoonseok.py
- BOJ/15686-치킨_배달/15686-치킨_배달-yoonseok.py
- BOJ/16953-A_→_B/16953-A_→_B-yoonseok.py
- BOJ/17070-파이프_옮기기_1/17070-파이프_옮기기_1-yoonseok.py
> 22.08.28 (yoonseok)

- BOJ/15686-치킨_배달/15686-치킨_배달-eonyong.py
- BOJ/16953-A_→_B/16953-A_→_B-eonyong.py
- BOJ/17144-미세먼지_안녕!/17144-미세먼지_안녕!-eonyong.py
> 22.08.27(eonyong)

- BOJ/03190-뱀/03190-뱀-eonyong.py
- BOJ/13458-시험_감독/13458-시험_감독-eonyong.py
- BOJ/14499-주사위_굴리기/14499-주사위_굴리기-eonyong.py
- BOJ/14501-퇴사/14501-퇴사-eonyong.py
- BOJ/17144-미세먼지_안녕!/17144-미세먼지_안녕!-eonyong.py
> 22.09.03 (eonyong)

- BOJ/13458-시험_감독/13458-시험_감독-yoonseok.py
- BOJ/14500-테트로미노/14500-테트로미노-yoonseok.py
- BOJ/14501-퇴사/14501-퇴사-yoonseok.py
> 22.09.07 (Yoonseok)

- BOJ/01107-리모컨/01107-리모컨-eonyong.py
- BOJ/14502-연구소/14502-연구소-eonyong.py
- BOJ/14503-로봇_청소기/14503-로봇_청소기-eonyong.py
- BOJ/14888-연산자_끼워넣기/14888-연산자_끼워넣기-eonyong.py
- BOJ/14889-스타트와_링크/14889-스타트와_링크-eonyong.py
> 22.09.14(Eonyong)

- BOJ/15683-감시/15683-감시-yeonju.py
- BOJ/15684-사다리_조작/15684-사다리_조작-yeonju.py
> 22.09.19 (yeonju)

- BOJ/14891-톱니바퀴/14891-톱니바퀴-eonyong.py
- BOJ/15683-감시/15683-감시-eonyong.py
- BOJ/15684-사다리_조작/15684-사다리_조작-eonyong.py
> 22.09.16 (eonyong)

- BOJ/16234-인구_이동/16234-인구_이동-yoonseok.py
- BOJ/16235-나무_재테크/16235-나무_재테크-yoonseok.py
- BOJ/16236-아기_상어/16236-아기_상어-yoonseok.py
> 22.09.26 (yoonseok)

- BOJ/16234-인구_이동/16234-인구_이동-eonyong.py
- BOJ/16236-아기_상어/16236-아기_상어-eonyong.py
- BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-eonyong.py
> 22.09.26 (Eonyong)

- BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-eonyong.py
- BOJ/17142-연구소_3/17142-연구소_3-eonyong.py
- BOJ/17779-게리맨더링_2/17779-게리맨더링_2-eonyong.py
- BOJ/17822-원판_돌리기/17822-원판_돌리기-eonyong.py
> 22.09.30 (eonyong)

- BOJ/17142-연구소_3/17142-연구소_3-yoonseok.py
- BOJ/17825-주사위_윷놀이/17825-주사위_윷놀이-yoonseok.py
- BOJ/17837-새로운_게임_2/17837-새로운_게임_2-yoonseok.py
> 22.10.03 (yoonseok)

- BOJ/21611-마법사_상어와_블리자드/21611-마법사_상어와_블리자드-eonyong.py
- BOJ/23288-주사위_굴리기_2/23288-주사위_굴리기_2-eonyong.py
- BOJ/23290-마법사_상어와_복제/23290-마법사_상어와_복제-eonyong.py
- BOJ/23291-어항_정리/23291-어항_정리-eonyong.py
> 22.10.09 (eonyong)

- BOJ/14891-톱니바퀴/14891-톱니바퀴-yoonseok.py
- BOJ/16234-인구_이동/16234-인구_이동-yoonseok.py
- BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-yoonseok.py
- BOJ/20056-마법사_상어와_파이어볼/20056-마법사_상어와_파이어볼-yoonseok.py
- BOJ/21608-상어_초등학교/21608-상어_초등학교-yoonseok.py
- BOJ/21609-상어_중학교/21609-상어_중학교-yoonseok.py
> 22.10.24 (yoonseok)

- BOJ/01005-ACM_Craft/01005-ACM_Craft-yoonseok.py
- BOJ/01197-최소_스패닝_트리/01197-최소_스패닝_트리-yoonseok.py
- BOJ/01202-보석_도둑/01202-보석_도둑-yoonseok.py
- BOJ/21608-상어_초등학교/21608-상어_초등학교-yoonseok.py
> 22.10.31 (yoonseok)

- BOJ/01509-팰린드롬_분할/01509-팰린드롬_분할-yoonseok.py
- BOJ/01806-부분합/01806-부분합-yoonseok.py
- BOJ/01987-알파벳/01987-알파벳-yoonseok.py
- BOJ/02143-두_배열의_합/02143-두_배열의_합-yoonseok.py
> 22.12.07 (Yoon seok)

- BOJ/02239-스도쿠/02239-스도쿠-yeonju.py
- BOJ/02252-줄_세우기/02252-줄_세우기-yeonju.py
> 22.12.13 (yeonju)
